[package]
name = "r-heatmap"
version = "0.1.0"
edition = "2024"
authors = ["joaopssx"]
description = "A CPU and system heatmap TUI by joaopssx"

[dependencies]
chrono = "0.4.44"
clap = { version = "4.5.60", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
fern = "0.7.1"
log = "0.4.29"
ratatui = "0.30.0"
serde = { version = "1.0.228", features = ["derive"] }
sysinfo = "0.38.2"
toml = "1.0.3"
